title: Notre-Dame de Paris
baseURL: https://nic1611.github.io/blog/
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: /resources
DefaultContentLanguage: pt
SectionPagesMenu: main
Paginate: 10
googleAnalytics: ''
enableRobotsTXT: yes
publishDir: /docs/
languages:
  pt:
    contentDir: content/pt
    title: Q.G do Tux
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: bg-black
  description: Venha para o lado tux da força.
  facebook: ''
  favicon: ''
  featured_image: /images/sean-lim.jpg
  github: ''
  gitlab: ''
  instagram: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 3
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: ''
  youtube: ''
