[build]
command = "hugo"
publish = "docs"

[build.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.82.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.82.0"


[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1

  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1