---
title: "Conexão ao PostgreSQL utilizando o R"
date: 2021-05-03
featured_image: https://images.unsplash.com/photo-1489875347897-49f64b51c1f8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80
tags:
- R
- postgreSQL
description: ""
authors: ["Nicolas Soffi"]
---

# Instalação do Pacote: RPostgres

O pacote RPostgres nos fornece uma interface simples para conectar à base de dados mantidas no PostgreSQL, utilizando o DBI. Ele é umpacote como outro qualquer e portanto, pode ser instalado com o seguinte comando:
```r
install.packages("RPostgres")
```
Ou ainda, ele pode ser instalado via interface gráfica do RStudio, utilizando a aba **Packages** e depois **Install**.
Para maiores informações sobre este pacote, consulte sua documentação disponível aqui (https://rpostgres.r-dbi.org/).

# Gerenciando uma Conexão

Para executar comandos SQL no PostgreSQL, o primeiro passo é abrir uma conexão com o um banco de dados desejado. A função paraisso é a dbConnect() e ela possui alguns parâmetros que são requeridos para efetuar a conexão ao PostgreSQL, a saber:

 - **user** - nome do usuário do PostgreSQL
 - **password** - senha do usuáriohost - endereço IP do PostgreSQL
 - **port** - número da porta de conexão (a porta padrão do PostgreSQL é a 5432)
 - **dbname** - nome do banco de dados que a conexão será estabelecida
 
A função dbConnect() irá retornar uma variável que contém todas as informações sobre sua conexão e ela será usada por todas asoutras funções do pacote RPostgres para que seja possível submeter consultas.

Para efetuar a conexão, usa-se a função dbDisconnect() passando como parâmetro a variável de conexão. Essa função deve serchamada somente após executar todos os comandos SQL de interesse. Caso você se disconecte da base de dados e tente submetercomandos SQL, ocorrerá um erro. Assim, sendo necessário estabelecer uma nova conexão.

Dessa forma (e seguindo os passos da seção de Introdução), podemos escrever o seguinte formato geral de programa em R queestabelece a conexão com o banco de dados usado na disciplina para executar diversos comandos SQL:

```r
library(RPostgres)
#aqui estamos definindo nossa conexão e atribuindo essa conexão à variável con
con <- dbConnect(Postgres(),                
                user = "postgres",                 
                password = "123",                 
                host = "localhost",                 
                port = 5432,                 
                dbname = "departamento")
                
#visualizando alguns dados sobre a conexão estabelecida
con
## <PqConnection> departamento@localhost:5432#depois de estabelecida a conexão, podemos executar aqui vários comandos SQL sobre a nossa base de dados!
#assim que terminarmos de executar todos os comandos SQL que nos interessad, devemos fechar a conexão:
dbDisconnect(con)
```

# Nota Importante

É importante enfatizar que no programa R anteriormente mostrado (e os que serão apresentados nesse material) utilizará uma formainsegura de estabelecer a conexão com um banco de dados no sentido de expor a senha de um usuário em um script. Este materialexpõe a senha somente para fins acadêmicos. Existem algumas formas de melhorar essa segurança em programas R:

  1. Se sua aplicação executa no RStudio, você pode usar o comando rstudioapi::askForPassword("Informe sua senha")(atribua essa função ao parâmetro **password**) para que uma caixa de diálogo no RStudio abra e o usuário consiga informar asenha.
  2. Manter a senha criptografada em um arquivo e fazer essa leitura pelo R, atribuindo o resultado no parâmetro (existe um pacotepara realizar tais criptografias: cyphr (https://www.rdocumentation.org/packages/cyphr/versions/1.1.0)).
  
Tais tópicos fogem do escopo da disciplina, porém são dadas essas opções de soluções como forma de complementar o assunto.
  
# Comandos básicos do Pacote RPostgres

O pacote RPostgres possui diversas funções que podem nos ajudar a relembrar a estrutura de nosso banco de dados e até mesmorecuperar dados de forma mais fácil (sem precisar submeter comandos em SQL).

De uma forma prática, o código abaixo demonstra vários desses comandos:

```r
library(RPostgres)
con <- dbConnect(Postgres(),                 
                  user = "postgres",                 
                  password = "123",                 
                  host = "localhost",                 
                  port = 5432,                 
                  dbname = "departamento")

#a função abaixo lista todas as tabelas do banco de dados conectado
dbListTables(con)
## [1] "empregado"         "departamento"      "localizacao_depto"
## [4] "projeto"           "trabalha"          "dependente"

#a função abaixo lista todas os atributos de uma tabela específica
dbListFields(con, "empregado")
##  [1] "primeironome"   "inicialmeio"    "ultimonome"     "numempregado"  
##  [5] "datanascimento" "endereco"       "sexo"           "salario"       
##  [9] "numsupervisor"  "numdepto"

#a função abaixo retorna todos valores de uma tabela específica como um data.frame
dbReadTable(con, "empregado")

dbDisconnect(con)
```
 
Existe também a função dbWriteTable() que escreve um data.frame diretamente no banco de dados conectado. Assim, ela recebetrês parâmetros: a conexão, nome da tabela como string e o data.frame. Há também a função dbRemoveTable() que removeuma tabela do banco de dados (informando como parâmetro a conexão e o nome da tabela como string).

# Execução de Instruções SQL

A seguir, este material mostra como executar comandos que não recuperam dados (ou seja, comandos de inserção, alteração e remoção)bem como comandos que recuperam dados como data.frame (que podem ser convertidos como tibble).

# Inserção, Alteração e Remoção

Para executar um comando SQL que não recupera dados, usa-se a função dbExecute(). Essa função retorna o número de registros(tuplas) que foram afetadas pelo comando SQL executado (ou ainda, o valor do RETURNING - ver exemplo). Usualmente, essa função éusada para executar uma instrução SQL (que pode ser parametrizada).

A seguir, são apresentados alguns exemplos de execução de comandos de inserção (inclusive inserção em lote), alteração e remoção de dados:

```r
library(RPostgres)
con <- dbConnect(Postgres(),                 
                  user = "postgres",                 
                  password = "123",                 
                  host = "localhost",                 
                  port = 5432,                 
                  dbname = "departamento")
                  
#verificando os dados atuais da tabela dependente
dbReadTable(con, "dependente")
```
```r
#inserindo um novo filho para o empregado com código 3
dbExecute(con, "INSERT INTO dependente(numempregado, nomedependente, sexo, dataaniversario, parentesco) VALUES           (3, 'Julio', 'M', '2020-05-10', 'filho')")
## [1] 1

#Lembre-se que vários registros podem ser inseridos com uma mesma instrução INSERT INTO (separando os parênteses depois do VALUES usando vírgula). Por exemplo, inserindo 2 filhos para o empregado 4
dbExecute(con, "INSERT INTO dependente(numempregado, nomedependente, sexo, dataaniversario, parentesco) VALUES           (4, 'Kevin', 'M', '2019-06-10', 'filho'),          
          (4, 'Kate', 'F', '2019-06-10', 'filho')")
## [1] 2

#Ainda, podemos realizar inserção em lote usando listas da linguagem R. 
#Por exemplo, seja a seguinte lista de valores a serem inseridos como dependentes do empregado 6 e 3. Se fossémos fazer do jeito tradicional, precisaríamos de 2 instruções INSERT INTO. Entretanto, vamos fazer por meio de parametrização.
#Primeiro, definimos uma lista, que deve possuir o mesmo número de colunas da tabela dependente, seguindo a mesma ordem das colunas a serem definidas na parte do INSERT INTO e cada elemento dessa lista é prirmeiro um vetor com mesmo número de valores
deps <- list(c(6, 6, 3, 3),                
              c("André", "Marca", "Fabiacino", "Andrea"),               
              c("M", "F", "M", "F"),                
              c("2019-05-02", "2017-06-03", "2018-07-10", "2018-07-10"),                
              c("conjuge", "filho", "filho", "filho"))

#perceba o formato da lista criada (que reflete a estrutura da tabela em que seus valores serão inseridos em lote):
deps
## [[1]]
## [1] 6 6 3 3
## 
## [[2]]
## [1] "André"     "Marca"     "Fabiacino" "Andrea"   
## 
## [[3]]
## [1] "M" "F" "M" "F"
## 
## [[4]]
## [1] "2019-05-02" "2017-06-03" "2018-07-10" "2018-07-10"
## 
## [[5]]
## [1] "conjuge" "filho"   "filho"   "filho"

#inserção em lote (os $x, onde x vai de 1 até 5, serão trocados por cada valor correspondente da lista definida)
dbExecute(con, "INSERT INTO dependente(numempregado, nomedependente, sexo, dataaniversario, parentesco) VALUES ($1, $2, $3, $4, $5)", params = deps)
## [1] 4
#checando as inserçõesdbReadTable(con, "dependente")
```
```r
#vamos excluir os dependentes do funcionário chamada Ana Silva
dbExecute(con, "DELETE FROM dependente WHERE numempregado IN (SELECT numempregado FROM empregado WHERE primeironome = 'Ana' AND ultimonome = 'Silva')")
## [1] 3

#vamos alterar o sexo do dependente chamado Vicente do numempregado 4
dbExecute(con, "UPDATE dependente SET sexo = 'M' WHERE numempregado = 4 AND nomedependente = 'Vicente'")
## [1] 1

#checando as remoções e alteração
dbReadTable(con, "dependente")
```

```r
dbDisconnect(con)
```

**IMPORTANTE: Se você executar o trecho de código acima mais de uma vez, você encontrará um erro nas inserções. Isso se deve aofato de que você estará tentando incluir dados repetidos em colunas que são únicas (chaves primárias). Então, cuidado.**

Por debaixo dos panos, a função dbExecute() realiza as seguintes tratativas: (i) envia o comando SQL ao PostgreSQL, (ii) captura onúmero de linhas afetadas pelo comando, e (iii) libera o resultado em memória (deixando apenas a cópia para o R). Isso poupa otrabalho de chamar três funções de forma consecutiva ao RPostgres (ou seja, dbSendStatement(), dbGetRowsAffected() edbClearResult()). Então, recomenda-se, para fins comuns, a utilização da função dbExecute() para execução de comandosvariados que não resultam na recuperação de dados.

### Nota Importante

O uso de parâmetrização (ou seja, $x no comando SQL e então a especificação do valor como parâmetro usando o params) é umaprática para evitar SQL Injection (https://pt.wikipedia.org/wiki/Inje%C3%A7%C3%A3o_de_SQL). Esse tipo de tópico vai também além doescopo da disciplina, porém é importante saber sobre seu risco e como evitar. Para a disciplina, não é necessário usar comandosparametrizados.

# Execução de Comandos que Retorna Dados

Várias instruções SQL podem recuperar dados de um banco de dados. Dessa forma, devemos usar a função dbGetQuery(), a qualretorna um data.frame. A execução de consultas SQL é o clássico exemplo de recuperação de dados de um banco de dados.Entretanto, outros comandos podem recuperar dados, tal como a instrução INSERT INTO como será visto em seguida.

# Consultas

A seguir, são apresentados alguns exemplos de execução de consultas SQL (SELECT). O data.frame resultante pode ser convertidopara um tibble que pode ser usado por outros pacotes do R (como tidyverse) visando sua manipulação e visualização.

```r
library(RPostgres)
library(tidyverse) 
#pois iremos usar tibble

on <-dbConnect(Postgres(),                 
                user = "postgres",                 
                password = "123",                 
                host = "localhost",                 
                port = 5432,                 
                dbname = "departamento")
                
#executando a seguinte consulta:
# Recupere todos os departamentos e suas localizações#a função as_tibble converte o resultado da função dbGetQuery para um tibble

projetos <- as_tibble(dbGetQuery(con, "SELECT nomedepto, localizacao                        
                                        FROM departamento d, localizacao_depto l                       
                                        WHERE d.numdepto = l.numdepto"))

projetos
```

```r
#executando a seguinte consulta:
# Retorne o nome do departamento, a média salárial, bem como o salário mínimo e máximo, de todos osempregados que trabalham em um departamento com mais de 3 empregados, agrupando por departamento. Ordene, em ordem descendente, pela média:

media_salarial <- as_tibble(dbGetQuery(con,"SELECT nomedepto, AVG(salario) media, MIN(salario) min, MAX(salario) maxFROM empregado e, departamento dWHERE e.numdepto = d.numdeptoGROUP BY nomedeptoHAVING COUNT(nomedepto) > 3ORDER BY media desc"))

media_salarial

dbDisconnect(con)
```

**IMPORTANTE: Se você modificou sua base de dados, os resultados aqui poderão ser diferentes.**

Por debaixo dos panos, a função dbGetQuery() realiza as seguintes tratativas: (i) envia o comando SQL ao PostgreSQL, (ii) captura oresultado para uma variável, e (iii) libera o resultado em memória (deixando apenas a cópia para o R). Isso poupa o trabalho de chamartrês funções de forma consecutiva ao RPostgres (ou seja, dbSendQuery(), dbFetch() e dbClearResult()). Então, recomenda-se,para fins comuns, a utilização da função dbGetQuery() para execução de comandos variados que resultam na recuperação de dados.

# Recuperação de Dados a partir de Inserção

A seguir, veremos que o comando INSERT INTO pode também recuperar dados. Isso ocorre quando temos uma coluna que usasequência para definir seus valores, tal como quando definimos a chave primária de uma tabela usando o tipo SERIAL. Vimos quepodemos usar funções do PostgreSQL para capturar valores da sequência.

Aqui iremos ver como capturar o valor gerado por uma coluna que usou o tipo SERIAL em sua definição (que no fundo é umasequência) logo após UMA inserção. Isso é útil para inserção de um registro em uma tabela e a utilização de seu identificador único parainserir um segundo registro.

Isso é mostrado no exemplo abaixo:

```r
library(RPostgres)

con <- dbConnect(Postgres(),                 
                  user = "postgres",                 
                  password = "123",                 
                  host = "localhost",                 
                  port = 5432,                 
                  dbname = "departamento")
                  
#verificando os dados atuais da tabela departamento
dbReadTable(con, "departamento")
```

```r
#verificando os dados atuais da tabela localizacao_Depto
dbReadTable(con, "localizacao_depto")
```

```r
#inserindo um departamento e retornando o numdepto gerado pela sequência usada (lembre-se que o numdepto foi definido como SERIAL; com isso, uma sequência é associada a coluna numdepto, gerando números sequenciais. Podemos capturar o valor gerado para essa inserção usando o RETURNING no final do comando INSERT INTO.)

id <- dbGetQuery(con, "INSERT INTO departamento(nomedepto, numgerente) VALUES ('TI', 2) RETURNING numdepto")
id 

#repare que ele é um data.frame e podemos capturar seu valor (único) por meio do operador $

#agora vamos inserir a localização desse departamento inserido. Repare no uso da parametrização para associar um valor. Poderíamos também montar a string com o comando, por exemplo, usando a função de concatenação paste0()
dbExecute(con, "INSERT INTO localizacao_depto(numdepto, localizacao) VALUES ($1, 'DV')", params = id$numdepto)
## [1] 1

#verificando os dados após a inserção
dbReadTable(con, "departamento")

#verificando os dados após a inserção
dbReadTable(con, "localizacao_depto")

dbDisconnect(con)
```

# Conclusão

Este material integra os conceitos do projeto físico de banco de dados em uma aplicação implementada em R. Em geral, os conceitosvistos aqui se aplicam à outras linguagens de programação, porém, claro, mudando a sintaxe e nome de funções.

Uma dica geral é deixar o Sistema Gerenciador de Banco de Dados fazer todo o trabalho “sujo” e somente tratar e visualizar os dados nolado da aplicação. 



